### PR TITLE
Https resolution based on url

### PR DESCRIPTION
**Pull request by jonocodes**
Updated scheme resolution to use the incoming url even if schemes are defined

### CODE REVIEW

**Comment by fehguy** [comment]
Seems like it should check `this.schemes[0]` before `location.scheme` as that is the intent of the API

**Comment by jonocodes** [comment]
Sure, the order can be switched. Is it safe to assume that when you add two schemes in the spec, that the order they are inserted is preserved? This way schemes[0] is deterministic. Just making sure.

**Comment by fehguy** [comment]
yes

**Comment by jonocodes** [comment]
Pull request updated

**Pull request merged**
