### PR TITLE
Fix: Make collectionFormat work for array parameters when post form data

### PR DESCRIPTION
**Pull request by birbird**
The test need to be improved.
I don't know how to form a 'multi/part' post operation.
The test I added is 'application/x-www-form-urlencoded' actually.

### CODE REVIEW

**Comment by birbird** [comment]
Fix test break

**Comment by cbornet** [comment]
:+1:  need this

**Comment by jeevanrd** [comment]
Facing the same issue here.  Any update on this???

**Comment by dakisa91** [comment]
Im using swagger-ui and it seems to me that this bug is present there too.

**Comment by fehguy** [comment]
This should be supported in master now.

**Pull request closed without merging**
