### PR TITLE
feat(build-request): Add support for openIdConnect

### PR DESCRIPTION
**Pull request by lipnitsk**
Securities are to be formatted the same way as oauth2, since OIDC is
just a layer on top of oauth2.

### CODE REVIEW

**Review by char0n — APPROVED** [review]
Thank you for contributing. Looks legit!

**Comment by lipnitsk** [comment]
@char0n thanks, I have just rebased on latest master for an easier merge!

**Comment by lipnitsk** [comment]
Is something wrong with the "Merge me!" CI task?
```
/home/runner/work/_actions/ridedott/merge-me-action/master/node_modules/@actions/github/lib/internal/utils.js:23
const httpClient = __importStar(require("@actions/http-client"));
^
Error: Parameter token or opts.auth is required
    at Object.httpClient [as getAuthString] (/home/runner/work/_actions/ridedott/merge-me-action/master/node_modules/@actions/github/lib/internal/utils.js:23:1)
    at Object.getOctokitOptions (/home/runner/work/_actions/ridedott/merge-me-action/master/node_modules/@actions/github/lib/utils.js:44:1)
    at Object.context [as getOctokit] (/home/runner/work/_actions/ridedott/merge-me-action/master/node_modules/@actions/github/lib/github.js:25:8)
    at Object.trim (/home/runner/work/_actions/ridedott/merge-me-action/master/src/index.ts:16:31)
    at exports (/webpack/bootstrap:9:1)
    at __webpack_require__ (/webpack/bootstrap:35:1)
    at module.exports.2 (/webpack/bootstrap:35:1)
    at /webpack/bootstrap:38:1
    at Object.<anonymous> (/home/runner/work/_actions/ridedott/merge-me-action/master/dist/index.js:7:28)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
```

**Comment by char0n** [comment]
@lipnitsk we've utilized automerge strategy for @dependabot PRs. This seems like a issue with persmission. Your PR cannot see our token. The merge me! GA IMHO shouldn't even run on PRs not issued with dependabot. Working on fix.

**Comment by char0n** [comment]
Problem fixed by https://github.com/swagger-api/swagger-js/commit/7e43c5b5d13fab89f3da1745bb9401cd66f1e821

**Pull request merged**
