### PR TITLE
Add individual content-types for each multipart/formdata part

### PR DESCRIPTION
**Pull request by mateusbandeiraa**
### Description
Addresses #2954

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mateusbandeiraa** [comment]
This is my first contribution to this project, so bear with me. I could use some help with making sure I'm not breaking anything with this change.

**Comment by char0n** [comment]
Switching from draft to standard PR

**Comment by char0n** [comment]
I have added `import { Blob } from 'formdata-node';` line as this library is isomorphic, which means it needs to run in Node.js and in browsers. This change make it possible to run in both environments. After this change the tests were run, but your code introduces a regression.

**Comment by char0n** [comment]
@mateusbandeiraa  are you willing to continue with this PR?

**Comment by mateusbandeiraa** [comment]
Yes. Will try to push something later this week.

**Comment by mateusbandeiraa** [comment]
I spent more time studying the code base and I think the fix should be in a different place; `buildFormData()` seems more appropriate. I can even see that for some cases, `Blob` objects are already being used. It's a matter of adding the `{ type: contentType }` argument to the constructor.
https://github.com/swagger-api/swagger-js/blob/1df1de9068a93bcdc0aeecf87eccb55ad829b6b2/src/http/index.js#L333-L368

I'm trying to figure out the cases in which the content type argument should be included. For times where it's explicitly defined in the spec it's obvious, but I think there are default values that can be omitted. (Look for "Encoding Object" at https://swagger.io/specification/).

Still trying to figure this out.

**Comment by mateusbandeiraa** [comment]
Still working on it, probably there's a tidier way to do this. Pushed to get the results from the status checks. Comments are welcome (maybe I'm spending too much of my time on something that wouldn't work?)

**Comment by char0n** [comment]
@mateusbandeiraa thanks for the PR, but we need to replace it with https://github.com/swagger-api/swagger-js/pull/3078

**Justification:** swagger-client facilitates request building and execution for SwaggerUI so we have to be aware how the built requests are later used. With changes in this PR, it would not be possible to pull original data encoded in `File` or `Blob` instances in synchronous way. 

The [PR](https://github.com/swagger-api/swagger-js/pull/3078) that replaces this one, introduced a sub-class of `File` which makes it possible to extract original data from `File` instances in synchronous way to support for example building the `curl` commands for SwaggerUI.

**Comment by char0n** [comment]
Addressed in SwaggerUI by https://github.com/swagger-api/swagger-ui/pull/9105

**Pull request closed without merging**
