### PR TITLE
Support x-tokenName extension in OpenAPI 3.0 specs

### PR DESCRIPTION
**Pull request by Shados**
### Description
Enables using `x-tokenName` in OpenAPI 3.0 OAuth security schemes in order to select a different field from the token JSON for use as the bearer token.

### Motivation and Context
Fixes swagger-api/swagger-ui#4084.

### How Has This Been Tested?
I've added a test case for it that provides both the default `access_token` and a non-default `id_token`, and confirms the latter is used.

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
    - Something about my environment doesn't play well with most of the tests, causing failures via timeout, but the new and all existing `test/oas3/execute` tests pass.

### CODE REVIEW

**Comment by shockey** [comment]
thanks @Shados! 👍

**Comment by JacobAtchley** [comment]
@shockey when can we expect a release for this? it appears npm is hasn't been updated yet 😭

**Comment by webron** [comment]
@JacobAtchley https://www.npmjs.com/package/swagger-client/v/3.10.0 :)

**Comment by JacobAtchley** [comment]
@webron 🙏 thank you!

**Pull request merged**
