### PR TITLE
Add same-origin credentials policy to makeFetchJSON

### PR DESCRIPTION
**Pull request by dylancwood**
Adds [credentials: same-origin](https://github.com/github/fetch#sending-cookies) to resolved fetch options. This will instruct the browser to send cookies and authorization headers when fetching external definitions.

Existing issue: https://github.com/swagger-api/swagger-js/issues/1025
Symptom issue in swagger-ui: https://github.com/swagger-api/swagger-ui/issues/3220

Note on testing: Since these tests do not run in a browser, it would be difficult to assert that cookies are being set properly in a test. We could however create a spy that ensures that `fetch` is getting the `credentials: same-origin` option passed to it. 

@shockey

### CODE REVIEW

**Comment by dylancwood** [comment]
@shockey: What do you think of this? I'm sure you've got lots of other stuff going on, so I understand that you can't review everything right away. Just replying here to bring this back to the top of your inbox.

Thanks in advance.

**Comment by shockey** [comment]
I get that this solves a problem with authentication, which is good.

My concern is that this lessens the amount of control that we have over the request... the browser will attach cookies to all requests to the origin, which could get weird when using Try-It-Out, if your API is on the origin.

To sidestep all this, we _could_ set `credentials: "same-origin"` only when resolving references.

**Comment by dylancwood** [comment]
@shockey: I agree: we should only do it when resolving references. To be honest, that is what I assumed this did: it is in `resolver.js` after-all. Let me know if that is not the case.

**Comment by shockey** [comment]
@dylancwood,



You're right, this is only for the resolver. My apologies!

In that case, this looks OK to me. Going to add a couple reviewers ( @webron @ponelat ).

**Comment by dylancwood** [comment]
Thanks. Any genius ideas on testing this to avoid regressions in the future? This is a little tricky, since it is just an option passed to a third-part lib (`isomorphic-fetch`). That option then has a side-effect in the browser, which we cannot test directly in node (it's not worth it anyway).

**Comment by shockey** [comment]
@dylancwood We'd need to start doing browser testing, which is something I've wanted for our whole suite for a while.

I'm pretty sure that our current tests would catch a leaking credentials attachment if they were run in a browser context, so new tests may not be required. 

Getting a node test suite running in the browser may not be trivial, though.

**Pull request merged**
