### PR TITLE
Fix for #629 content type for get with body

### PR DESCRIPTION
**Pull request by mgttlinger**
This should fix issue #629

### CODE REVIEW

**Comment by mgttlinger** [comment]
The failing test does not seem to be an issue introduced by me

**Comment by mgttlinger** [comment]
@fehguy Would it generally be better to check if there is a body in the request and then use the selected content type regardless of the http method in use, instead of whitelisting every method individually (which has so far introduces 2 bugs)?

**Comment by fehguy** [comment]
can you explain more?

**Comment by mgttlinger** [comment]
Currently there is an if clause which checks the request method. If it is "post", "put", "patch" it sets the content type from the opts object (if there is one specified). If it is a "delete" it also checks if there is a body which was introduces due to https://github.com/swagger-api/swagger-ui/issues/1435. From my commit it now also does the same if it is a "get" request with a body. My idea was to not check the request method at all but check if there is a body instead.

**Pull request merged**
