### PR TITLE
Make Git ignore temporary files

### PR DESCRIPTION
**Pull request by ehmicky**

### CODE REVIEW

**Comment by whitlockjc** [comment]
Thanks.  _(This is a trivial change so it was merged.)_

**Comment by whitlockjc** [comment]
@fehguy I just realized that this was merged to `develop_2.0`...was that what we wanted?

**Comment by webron** [comment]
@whitlockjc - yeah, it's fine. thanks.

**Comment by whitlockjc** [comment]
Well then we're good.  :)  Thanks @webron.

**Pull request merged**
