### PR TITLE
Fix '&' adding to url if param is empty

### PR DESCRIPTION
**Pull request by kojoru**
This is a fix to https://github.com/swagger-api/swagger-ui/issues/959

### CODE REVIEW

**Comment by kojoru** [comment]
I'm not sure how to go about testing the commit. There are no apis in petstore which offer 2+ optional query params. Should I add some new operations to sample API?

**Comment by fehguy** [comment]
Take a look at the test/operation.js and you should see how to mock your own operations and test the generated query string

**Comment by kojoru** [comment]
Can't do that since that's a 1.x-only bug.

**Comment by kojoru** [comment]
I can't access SwaggerOperation from swagger-compat.js, can I?

**Comment by kojoru** [comment]
I did eventually write tests with adding new operation to the 1.2 spec. Please let me know if there's a better way.

**Comment by fehguy** [comment]
Yes I didn't notice this was for 1.2. For now yes, adding an operation is the best way

**Comment by kojoru** [comment]
Ok, let me know if there's anything I need to do for it to be merged.

**Pull request merged**
