### PR TITLE
Enabled parsing YAML from URL parameter.

### PR DESCRIPTION
**Pull request by NicholasRBowers**
This commit addresses [this issue](https://github.com/swagger-api/swagger-js/issues/525).

### CODE REVIEW

**Comment by NicholasRBowers** [comment]
Sorry, I didn't realize that the file I edited was a compiled file -_-

Which source file compiles to this bit of code?

```
request.parse = {
  'application/x-www-form-urlencoded': parseString,
  'application/json': JSON.parse
};
```

I can't seem to locate it.

**Comment by ponelat** [comment]
I'll see if I can't find it, but you can try grepping for it (text search) on the files under src/js

**Comment by NicholasRBowers** [comment]
Tried that. I wasn't getting ANY hits :/

**Comment by ponelat** [comment]
I think I know why.... it might not be part of swagger at all, it looks like superagent (http lib)
We don't use JSON.parse in swagger, we've replaced it with js-yaml (which handles both json and yaml)

here is your line...https://github.com/visionmedia/superagent/blob/360ca37c0ffa775f3e788a39a109584f1accc286/lib/client.js#L182

**Comment by fehguy** [comment]
since this affects dependent libraries, i'm closing the issue.

**Pull request closed without merging**
