### PR TITLE
Restore swagger2 support for x-tokenName extension in OAuth2 security

### PR DESCRIPTION
**Pull request by ngraef**
### Description

The previously supported `x-tokenName` can be used in order to select another field from the token JSON as bearer token.

### Motivation and Context

As noted in [`swagger-ui`#4084](https://github.com/swagger-api/swagger-ui/issues/4084), v2 supported the `x-tokenName` spec extension to allow for tokens other than `access_token` to be used for "Try it Out" requests with OAuth2 security. Most notably, this allows for the selection of the `id_token` for service authorization. This PR restores that functionality for swagger2 specs.

### How Has This Been Tested?

Added a test case that uses `id_token` for authentication.

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
Code changes look good - handing off to @webron for consideration of the feature as a whole

**Comment by ngraef** [comment]
Thanks for reviewing! Any thoughts, @webron?

**Comment by webron** [comment]
I don't object to bringing back functionality that was supported in previous versions of Swagger-UI but...

- We should consider adding extension functionality support in plugins (and yes, @shockey, that would mean a plugin repository).
- We should consider renaming the extension name based on some work the OAI is doing right now on formalizing extensions, but I'd need to check the status of that.

**Comment by ngraef** [comment]
> We should consider renaming the extension name based on some work the OAI is doing right now on formalizing extensions

This PR adds the `x-tokenName` extension support exclusively for swagger 2 docs. OAI work would only impact the 3.x spec, right?

**Comment by shockey** [comment]
> This PR adds the x-tokenName extension support exclusively for swagger 2 docs. OAI work would only impact the 3.x spec, right?

@ngraef, yep, fair point. Let's move forward with this one.

**Comment by shockey** [comment]
thanks @ngraef!

**Pull request merged**
