### PR TITLE
Use .buffer() for binary responses when .blob() is not available

### PR DESCRIPTION
**Pull request by kevinoid**
This PR implements the fix requested in https://github.com/swagger-api/swagger-js/issues/979#issuecomment-290249977 by using `.buffer()` to get the binary response body when `.blob()` is not available, which occurs with `node-fetch` prior to version 2 (currently in alpha).

It also fixes the existing test for `serializeRes` which would always pass due to not returning the Promise value it created.  If you would prefer this to be split into a separate PR, let me know.

Thanks,
Kevin

### CODE REVIEW

**Comment by buunguyen** [comment]
Hi, the new tests are failing. Can you check?

BTW, some old tests fail, not because your code, I've merged the fixes to master already. Be sure to pull from upstream and run test locally.

Thanks!

**Comment by kevinoid** [comment]
The new `serializeRes` tests passed in https://travis-ci.org/swagger-api/swagger-js/jobs/216616487  I rebased against the master branch fixes and the tests are passing on my machine.  Should pass after the next Travis run.

**Comment by kevinoid** [comment]
https://travis-ci.org/swagger-api/swagger-js/builds/216618260 is complete.  The failure on Node 4.7 is due to use of `const` in strict mode in `src/server.js` which is not modified by this PR.

**Comment by buunguyen** [comment]
Interesting, the error is in a lib, fetch-mock...  Wondering why. I'll check locally.

```js
/home/travis/build/swagger-api/swagger-js/node_modules/fetch-mock/src/server.js:2
const fetch = require('node-fetch');
```

**Comment by kevinoid** [comment]
Ah, right you are.  I thought `src/server.js` was in this package.  Good catch.

**Comment by buunguyen** [comment]
Ha! Local works. Turn out Travis use 0.10 even though the env is set to 4.7. Probably a Travis bug. But your code is good. If you don't mind, please make this minor change:

Replace
```js
export function serializeRes(oriRes, url, {loadSpec = false}) {
```

With
```js
export function serializeRes(oriRes, url, {loadSpec = false} = {}) {
```

And then modify the tests so that it doesn't supply the empty object.

I'll deal with Travis and merge this PR later. Thanks!

**Comment by kevinoid** [comment]
Sure thing.  Done.  Let me know if you see anything else.  Thanks!

**Comment by buunguyen** [comment]
Thanks! I've fixed Travis, so the mystic error with fetch-mock has gone away. But your tests are failing in Node 4 (works in Node 6). Can you check?

**Comment by kevinoid** [comment]
That took some digging, but I think I've fixed it.  Waiting on the test results to confirm.

**Comment by buunguyen** [comment]
Good stuff, thank you!

**Comment by kevinoid** [comment]
My pleasure.  Thank you for reviewing and merging it!

**Pull request merged**
