### PR TITLE
Fixed exceptions when spec has null http operations

### PR DESCRIPTION
**Pull request by csuich2**
See https://github.com/swagger-api/swagger-js/pull/269

### CODE REVIEW

**Comment by whitlockjc** [comment]
It seems there are test failures.  If you can get these resolved, we should be in good shape.

**Comment by csuich2** [comment]
Yep - they are passing locally so I am trying to figure out what the difference is. =)

**Comment by csuich2** [comment]
@whitlockjc I'm quite new to a lot of the tools here and seem to be stumped. Both of those tests are passing on my machine and the errors seem like the test is being executed without the first of the commits being in place (since the first commit fixed the issue and the second added tests).

Am I setting up the pull request wrong or is Travis-CI only testing with one of my commits and not both?

**Comment by csuich2** [comment]
Or could it be that I am not checking in swagger-client.js? Should I be committing that after I build?

**Comment by whitlockjc** [comment]
I'm looking into how the test suite works and it is currently brittle.  Can you update your commit to include the changes to `lib/swagger-client*.js` and see if that fixes things?

**Comment by csuich2** [comment]
Done. Looks like Travis-CI hasn't kicked off a new test yet.

**Comment by csuich2** [comment]
There we go. I initially tried to figure out whether I should commit the lib/* changes, but it looked like some commits didn't include that and I wanted to err on the side of caution.

**Comment by fehguy** [comment]
this should be covered already in the refactoring.

**Pull request closed without merging**
