### PR TITLE
Fixed issue displaying array types

### PR DESCRIPTION
**Pull request by mohsen1**
From https://github.com/swagger-api/swagger-ui/pull/876

### CODE REVIEW

**Comment by mohsen1** [comment]
There are some trailing space removal. Lets merge those too

**Comment by fehguy** [comment]
@mohsen1 can we get some tests around this?

**Comment by mohsen1** [comment]
@fehguy I just moved the change to here. I'm not sure what it really does. 

What `Property.prototype.sampleValue` does? Please guide me for writing tests

**Comment by whitlockjc** [comment]
This has been addressed in a different commit.

**Pull request closed without merging**
