### PR TITLE
Refactorings in auth.js

### PR DESCRIPTION
**Pull request by aurelian**
Small changes to make the code more understandable.

 * extract ```for``` loops to methods
 * removed extra parameter ```authorizations``` which was not used

This is #265 against ```develop_2.0``` branch.

### CODE REVIEW

**Comment by fehguy** [comment]
@whitlockjc can you look at this?

**Comment by aurelian** [comment]
ok... fixed merge conflict and ```git push -f``` it.

**Comment by whitlockjc** [comment]
I'll take a look.

**Comment by whitlockjc** [comment]
Do you mind doing a rebase?

**Pull request closed without merging**
