### PR TITLE
Adding nested object support for deepObject style

### PR DESCRIPTION
**Pull request by DarkSorrow**
Adding deepObject query parameters serialisation and fix error when a value was null in the object

### Description
Created a function to transform the object pass as deepObject stype to query parameters, it uses the same style serialisation as before.

### Motivation and Context
My company is using this style of GET method to make filtered query, it seems that many REST API use this method as well to benefit from cache and such. I've read the post such as #1385 and i know that you are talking about asking people from the draft to change this but i know a lot of people are already using this style so i thought i'll just contribute the code that worked for me.
Just like people use nutella to make ice cream instead of just their bread like the picture i suppose it is fine to let them use nested object in their get if they want this :x

### How Has This Been Tested?
Started using it in our production environement

### Types of changes

- [x] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ethlo** [comment]
Any progress in this area?

**Comment by DarkSorrow** [comment]
Well i'm using my code for deep objects since last year and it seems to be working pretty well for the different use case we had

**Comment by ethlo** [comment]
Thank you. Any reason why this is not merged yet? Having PRs hanging around for a year seems quite counter-productive :-)

**Comment by char0n** [comment]
Hi @DarkSorrow,

First of all thank you for contributing this change!

As mentioned in https://github.com/swagger-api/swagger-js/issues/1385 and subsequent discussion in https://github.com/OAI/OpenAPI-Specification/issues/1706 with no clear decision, at this point even with [OAS 3.1](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md) it is still not specified how to serialize deep nested structures using `deepObject`. 

This PR would force everybody using swagger-client to use the style of serialization that your company users. You can understand we are reserved to merge this PR. Ultimately, things like `deepObject` should be controlled via extensions, then plugins to implement the extended functionality, and should not be part of the core library.

At this point of time we will not proceed with merging this PR.

**Pull request closed without merging**
