### PR TITLE
Fix boolean false parameter

### PR DESCRIPTION
**Pull request by extempl**

### CODE REVIEW

**Comment by webron** [comment]
Thanks for the PR. What behavior do you see without the fix?

**Comment by extempl** [comment]
@webron actual behavior is missed parameter. `true` works properly here, so I added workaround for `false` only.

**Comment by extempl** [comment]
@webron so without fix added test will fail with `http://swagger.io/v1/pets/findByStatus` != `http://swagger.io/v1/pets/findByStatus?status=false`

**Comment by shockey** [comment]
Thanks for the PR, @extempl!

This will go live in the release we run later today.

**Pull request merged**
