### PR TITLE
chore(deps): bump formdata-node from 3.7.0 to 4.0.0

### PR DESCRIPTION
**Pull request by char0n**
Closes #2193

### CODE REVIEW

**Comment by octet-stream** [comment]
What was confusing about release notes?

**Comment by octet-stream** [comment]
I don't think this will work:

https://github.com/swagger-api/swagger-js/blob/72d297f5ea6d7c4297aeeeac6c4f61e203270b36/test/http/http-multipart.js#L260-L261

Probably replace

```diff
-expect(await itemEntries[0].text()).toEqual(file1.toString());
+expect(await itemEntries[0].text()).toEqual(await file1.text());
-expect(await itemEntries[1].text()).toEqual(file2.toString());
+expect(await itemEntries[1].text()).toEqual(await file2.text());
```

**Comment by char0n** [comment]
> I don't think this will work:
> 
> https://github.com/swagger-api/swagger-js/blob/72d297f5ea6d7c4297aeeeac6c4f61e203270b36/test/http/http-multipart.js#L260-L261
> 
> Probably replace
> 
> ```diff
> -expect(await itemEntries[0].text()).toEqual(file1.toString());
> +expect(await itemEntries[0].text()).toEqual(await file1.text());
> -expect(await itemEntries[1].text()).toEqual(file2.toString());
> +expect(await itemEntries[1].text()).toEqual(await file2.text());
> ```

Yeah, this change + other things.


Anyway this technically introduces breaking change for us. We need to find a way how to still support Buffer instances transparently and transform them into Blob types under the hood.

**Comment by char0n** [comment]
> What is confusing about release notes?

`Remove builtin multipart/form-data encoder and all related methods` - did not understood what it really means, but I guess it was because I haven't use it due to the fact we use form-data-encoder

` Remove support for Buffer and ReadStream (the one you might create with fs.createReadStream), you can use Blob, fileFromPath and fileFromPathSync to replace them.` - I see the word `Buffer` here, but didn't really know where to start. Needed   to inspect commits to understand that it means...eventually I found out: Buffer is not supported as a value of FormData

**Comment by char0n** [comment]
Thanks for heads up and comments, it helped me to process this more quickly!

Backward compatibility when using Buffers is still guaranteed.

**Comment by octet-stream** [comment]
> Remove builtin multipart/form-data encoder and all related methods - did not understood what it really means, but I guess it was because I haven't use it due to the fact we use form-data-encoder

Because form-data serialization is not the part of the FormData class, this change was made. Basically builtin encoder was separated to another package - `form-data-encoder`, so any HTTP client can use it or use it as a reference for their own implementation.

> I see the word Buffer here, but didn't really know where to start.

Because `FormData` takes only `string`, `Blob` and `File` as entry's value - I had to remove it. Previously Buffer was converted to `File` internally, because it basically `Uint8Array` and `Blob` accepts it as one of `blobParts`.

**Pull request merged**
