### PR TITLE
Dropped isomorphic-fetch in favor of cross-fetch (React Native compatible)

### PR DESCRIPTION
**Pull request by lquixada**

### CODE REVIEW

**Comment by shockey** [comment]
This should fix #1047 😄

**Comment by shockey** [comment]
@lquixada, I see this module is at `v0.0.8`, and you're the author - is this library production-ready?

**Comment by lquixada** [comment]
@shockey yes! we're using cross-fetch in major e-commerce sites in Brazil. It was created to fix
the same problem as the issue #1047. Also, [VulcanJS](http://vulcanjs.org) and [graphql-request](https://github.com/graphcool/graphql-request) are already using it.

But if any bug comes up, let me know and I'll fix it (or you can open a pr yourself :).

**Comment by lquixada** [comment]
conflicts solved!

**Comment by shockey** [comment]
Thanks, @lquixada!

**Pull request merged**
