### PR TITLE
Checking for the presence of an existing query string in the request URL before appending new params

### PR DESCRIPTION
**Pull request by jimwhimpey**
If you have a path defined with an query string then additional params should be prefixed with "&" rather than "?".

Here's an example: http://flickr.github.io/flickr-api-swagger/#!/Public/getFavoritesByPersonID

### CODE REVIEW

**Comment by fehguy** [comment]
ok, but having a path with a query param actually is forbidden by the spec.

**Comment by jimwhimpey** [comment]
Yeah. Unfortunately there's no way around it for us.

**Comment by fehguy** [comment]
OK this is harmless so I'll merge, even though it's not really within the spec intention.

**Comment by jimwhimpey** [comment]
😄

**Pull request merged**
