### PR TITLE
clean up the http stuff and make a fetch method injectable

### PR DESCRIPTION
**Pull request by Robbilie**
- fetch was marked legacy in the execute file, i guess because it was used in the tests instead of http
- i started to clean up the http file because it was missing semicolons, modifying arguments and some other stuff, might fix that in the other files at some point
- removed the regexes aswell and switched to a probably more performant and risk free string matching :)

i hope its ok that this is in one commit and i hope you guys didnt have plans for the fetch method but a friend and i were building a h2 proxy for which we ended up nearly completely copying the http file just to exchange the fetch method in it so if other people would like to exchange the fetch method with request.js or something else, this should allow them to do so…

all tests are passing btw :)

### CODE REVIEW

**Comment by webron** [comment]
@buunguyen do you have the capacity to look into this one?

@shockey will review it as well, regardless.

**Comment by Robbilie** [comment]
Any news on this front? :)

**Comment by webron** [comment]
@Robbilie sorry it didn't get into this week's release. We're a bit backlogged and have to prioritize the work. Thanks for putting this up though. Hoping to get this reviewed for next release.

**Comment by shockey** [comment]
> fetch was marked legacy in the execute file, i guess because it was used in the tests instead of http

I'm not aware of any clients using that parameter off the top of my hand, but removing it entirely would amount to a breaking change, which we'd really like to avoid for the time being - so `fetch` needs to stay. I'm open to making it easier for users to sub in their own implementation, though.

> i started to clean up the http file because it was missing semicolons, modifying arguments and some other stuff, might fix that in the other files at some point

We actually _don't_ use semicolons in this project on purpose 😅  Modifying parameter names is OK if it makes sense and doesn't introduce breaking changes, but I'd like to see that in its own PR.

> removed the regexes aswell and switched to a probably more performant and risk free string matching :)

This is good! I'd like to see this in its own PR, though. Tests would be nice as well.

---

I would've liked to provide a line-by-line review of your changes, but the noise from the semicolon changes made it difficult to spot the logic changes.

I know that reorganizing the code into different PRs is a lot to ask - but splitting into logical PRs makes it a lot easier to trace what changed when, and have topical discussion about changes.

I'm going to close this PR, but I look forward to seeing superseding PRs based on the work in this one.

Thanks!

**Comment by Robbilie** [comment]
https://github.com/swagger-api/swagger-js/pull/1098

includes the userFetch

regarding the regex changes, a friend tried a bit and got these results so i wont PR that for now:
```
function shouldDownloadAsTextOrig(contentType) {
  return /json/.test(contentType) ||
        /xml/.test(contentType) ||
        /yaml/.test(contentType) ||
        /text/.test(contentType)
}
/*
Orig|json x 11,477,916 ops/sec ±0.75% (91 runs sampled)
Orig|xml x 7,497,474 ops/sec ±0.52% (97 runs sampled)
Orig|yaml x 5,051,156 ops/sec ±0.68% (94 runs sampled)
Orig|text x 4,224,534 ops/sec ±0.39% (96 runs sampled)
*/

function shouldDownloadAsTextOne(contentType = "") {
  return ["json", "xml", "yaml", "text"].some(str => contentType.includes(str))
}
/*
One|json x 6,393,355 ops/sec ±0.62% (94 runs sampled)
One|xml x 4,242,619 ops/sec ±0.89% (94 runs sampled)
One|yaml x 2,880,927 ops/sec ±0.35% (95 runs sampled)
One|text x 2,286,908 ops/sec ±0.61% (93 runs sampled)
*/

function shouldDownloadAsTextTwo(contentType = "") {
    return /json|xml|yaml|text/.test(contentType)
}
/*
Two|json x 19,513,133 ops/sec ±0.29% (92 runs sampled)
Two|xml x 24,767,680 ops/sec ±0.70% (93 runs sampled)
Two|yaml x 24,596,672 ops/sec ±0.31% (94 runs sampled)
Two|text x 24,863,942 ops/sec ±0.68% (88 runs sampled)
*/

const shouldDownloadAsTextThree = (contentType = "") => /json|xml|yaml|text/.test(contentType)
/*
three|json x 20,038,598 ops/sec ±0.31% (93 runs sampled)
three|xml x 24,801,552 ops/sec ±0.68% (92 runs sampled)
three|yaml x 25,187,765 ops/sec ±0.47% (94 runs sampled)
three|text x 25,252,579 ops/sec ±0.67% (96 runs sampled)
*/
```

**Pull request closed without merging**
