### PR TITLE
Fix issue circular ref not resolved if baseDoc is provided

### PR DESCRIPTION
**Pull request by buunguyen**
"Fixes" https://github.com/swagger-api/swagger-ui/issues/2889 and https://github.com/swagger-api/swagger-ui/issues/2923.

### CODE REVIEW

**Comment by shockey** [comment]
Confirmed fix for https://github.com/swagger-api/swagger-ui/issues/2889 and https://github.com/swagger-api/swagger-ui/issues/2923. LGTM! Thanks for this @buunguyen.

**Comment by gaurav517** [comment]
I see same error in version 3.13.6.
 - OS: macOS
 - Browser: chrome
 - Version: 66.0.3359.181
 - Swagger-UI version: 3.13.6
 - Swagger/OpenAPI version: Swagger 2.0

In case of big nested request/response json spec, I get following in console after trying to expand the operation in swagger-ui and the section of operation shows endless spinner. After refreshing we see the operation details.

```
system.js:461 RangeError: Maximum call stack size exceeded
    at immutable.js:2405
    at Le.pe.withMutations (immutable.js:1353)
    at He (immutable.js:2405)
    at Le.set (immutable.js:2096)
    at nt (immutable.js:2780)
    at Ze.set (immutable.js:2686)
    at immutable.js:2651
    at immutable.js:3016
    at immutable.js:2699
    at Le.__iterate (immutable.js:2206)
```

**Comment by gaurav517** [comment]
created followup issue https://github.com/swagger-api/swagger-ui/issues/4637

**Comment by JavaHelper** [comment]
Could you please clarify what does "baseDoc" mean ? How can we skip that ?

**Comment by JavaHelper** [comment]
Issue has been raised here: https://stackoverflow.com/questions/57370292/swagger-system-js461-rangeerror-maximum-call-stack-size-exceeded-using-ma

**Pull request merged**
