### PR TITLE
The param is not given value when loop all formParams

### PR DESCRIPTION
**Pull request by yuxiaomin**
The variable param should be given value when looping the formParams.

### CODE REVIEW

**Comment by fehguy** [comment]
It doesn't need to be, because it's not used inside that loop?

**Comment by yuxiaomin** [comment]
@fehguy the param is used. In Line 608
`bodyParam.append(key, this.encodeQueryCollection(param.collectionFormat, key, value));
`
to get the collectionFormat of param. So it is necessary otherwise param is not correct.

**Comment by fehguy** [comment]
hmm so it is, i missed that!

**Comment by xoss** [comment]
Already part of #850

**Comment by fehguy** [comment]
Merged with #858

**Pull request closed without merging**
