### PR TITLE
Enable submitting cookies in CORS requests

### PR DESCRIPTION
**Pull request by RenukaFernando**
### Changes
- Change the value of `credentials` according to the value of `http.withCredentials` as in the `README.md`.

### Description
- Change the value of `credentials` if `http.withCredentials` value is `true`.

### Motivation and Context
- The issue is `credentials` is always 'same-origin' to fetch request.
- Cookies are not stored nor submitted across different origins.
- Fixes https://github.com/swagger-api/swagger-js/issues/1186

### How Has This Been Tested?
 - Tested with two origins.
 - UI running on `localhost:9292` sends requests to the server on `localhost:9293`.

### Screenshots (if appropriate):
- Video on testing the fix: [Testing swagger-js submitting cookies within two origins.](https://youtu.be/lXu1MR_Z730)
- Set cookies
  setcookie-header

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
@RenukaFernando, can you add some tests to cover this new functionality?

**Comment by RenukaFernando** [comment]
Hi @shockey,
As per our understanding, writing unit tests for this improvement is troublesome. Can you please help writing integration tests on this?
So then this can be merged.

**Comment by shockey** [comment]
@RenukaFernando can do!

**Comment by shockey** [comment]
thanks, @RenukaFernando!

**Comment by RenukaFernando** [comment]
Thank you! @shockey for you help

**Comment by RenukaFernando** [comment]
Hi @shockey,
We are still facing the issue of handling CORS request. https://github.com/swagger-api/swagger-js/pull/1236 is fixed the issue and we have tested it with two origins.

Can you please review it?

**Comment by dalbani** [comment]
Hi, maybe a silly question, but could someone explain me how to set this `http.withCredentials` flag in the context of `SwaggerUIBundle` (i.e. when deploying Swagger UI as shown on https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L41)?

**Comment by shockey** [comment]
@dalbani, this is a merged PR - if you need help please open a new support ticket 👍

**Pull request merged**
