### PR TITLE
honors spec content-type for POST requests when no body.  see https:/…

### PR DESCRIPTION
**Pull request by kwv**
https://github.com/swagger-api/swagger-js/issues/1022

### CODE REVIEW

**Comment by shockey** [comment]
The code looks good to me, but based on the discussion in #1022, it's not clear to me if this a use case we're going to support (sending content-type for empty POSTs).

@webron, would appreciate your input here 😄

**Comment by marjan-georgiev** [comment]
This feature is the only thing preventing us from using this library in our application. It would be great if it got merged in.

**Comment by shockey** [comment]
@webron, bump

**Comment by webron** [comment]
I'm not convinced this is the right solution, and will be closing the PR without merging. Merging this PR will cause, in some cases, completely invalid requests. If you take the `application/json` example, you're telling the API producer that you're sending it an `application/json`- making it try to parse an empty string as a JSON which is just not a valid JSON. I'd be happy to reconsider if someone shows concrete information as to why it should be allowed, but until then...

**Pull request closed without merging**
