### PR TITLE
Fixed exceptions when spec has null http operations

### PR DESCRIPTION
**Pull request by csuich2**
Fix for issue #268

### CODE REVIEW

**Comment by mohsen1** [comment]
Please make this PR to `develop_2.0` branch.

Thanks

**Comment by whitlockjc** [comment]
This fix is unnecessary, see my comments on #268.

**Comment by mohsen1** [comment]
Please make this pull request to `develop_2.0` branch.

Thanks

**Comment by whitlockjc** [comment]
Please update this to include unit tests as well.

**Comment by whitlockjc** [comment]
Did you mean to close this?  The pull request is valid and should be pulled as long as we can get a test that shows it works.

**Comment by csuich2** [comment]
Got it - just a misunderstanding. I've got a couple tests that are working. Just dealing with the branch changes. I'll submit a new pull request soon since @mohsen1 requested it to be for develop_2.0.

**Comment by whitlockjc** [comment]
Makes sense.  I just didn't want you to close this pull request, which is useful, because of the conversation we had in #268.  Even though the document that causes is invalid from a Swagger perspective, swagger-js should be resilient enough not to blow up in cases like this so your pull request is important.

**Comment by csuich2** [comment]
Bumping this. @whitlockjc - did you want to accept this?

**Comment by kungfoo** [comment]
I am actually stuck using swagger, because of this bug. Is it going to be merged soon?

**Comment by whitlockjc** [comment]
This needs to be rebased.  If you rebase it, I'll merge it immediately.

**Comment by fehguy** [comment]
OK this PR came to be because of an issue in the server sending nulls.  Even if accepted, it'll create other issues to have nulls.  Since the code has drifted (no fault but our own), I'm going to close this out and open another tracking issue to keep tabs on null issues in general.

**Pull request closed without merging**
