### PR TITLE
Feature/composition

### PR DESCRIPTION
**Pull request by fehguy**
Addresses #455.  Notes on this integration

* The primary use cases are for composing multiple objects and inheritence
* To track the "origin" of properties, we are using a vendor extension in the resolver, `x-resolved-from`.
* To track the "parents" of a composed object, we are using a vendor extension, `x-resolved-from` which contains an array of _locations_ from which the object was created

Limitations:
* multiple compositions are not supported.  They can be, but currently are not.
* The rendering support is not complete.  The objects will contain the necessary reference information, but the json sample & mock signatures are not added
* Others?

### CODE REVIEW

**Comment by fehguy** [comment]
This should address #188

**Comment by webron** [comment]
When you say multiple compositions are not supported, does that mean more than two entries in the `allOf` array, or nested `allOf` definitions?

**Comment by fehguy** [comment]
@webron nested are not supported.  It's not much work, but if we can push that to a dot release, I'd appreciate it.

**Comment by webron** [comment]
Sure, was just looking for a clarification. :+1:

**Pull request merged**
