### PR TITLE
Use title in models when available per swagger-ui #1104

### PR DESCRIPTION
**Pull request by hamx0r**
This change resolves swagger-ui #1104
https://github.com/swagger-api/swagger-ui/issues/1104

### CODE REVIEW

**Comment by whitlockjc** [comment]
Could you please add a test for this?  `test/models.js` is the place.

**Comment by hamx0r** [comment]
Behold: swagger-api/swagger-js/pull/344

**Comment by whitlockjc** [comment]
Can you merge the pull request in #345 and this one together so that you have one PR with the business logic and its test?  #345 will not pass without this merged so having them together makes most sense.

**Comment by hamx0r** [comment]
So, using the online editor, i can only edit one file per pull request.  I don't see a way of merging existing pull requests, so i'm left with pulling everything to my local machine and pushing it back.  Embarrassingly, I'm not able to get this to work.  I've done this:
```
git clone -b develop_2.0 https://github.com/swagger-api/swagger-js.git 
# edit models.js for source and test files
cd swagger-js
git commit
    On branch develop_2.0
    Your branch is up-to-date with 'origin/develop_2.0'.

    Changes not staged for commit:
            modified:   lib/types/model.js
            modified:   test/models.js

    no changes added to commit
# Not sure if this is an error in the commit

# Now push it
git push -u origin develop_2.0
Username for 'https://github.com': <my email>
Password for 'https://<my email>':
remote: Permission to swagger-api/swagger-js.git denied to <my email>.
fatal: unable to access 'https://github.com/swagger-api/swagger-js.git/': The requested URL returned error: 403
```

Am i denied from making changes this way?

**Comment by webron** [comment]
That's not quite how it works. When you modified the file, github automatically created a fork for you - https://github.com/hamx0r/swagger-js. If you want to modify the PR, you need to clone your fork and not this repository as you don't have push permissions directly to it.

Also, that's not how you commit using git as you need to stage your changes first. You can use the shortcut `git commit -a`, however, if your not proficient with git you can also use the github client (there's one for windows and mac, not sure about linux).

Remember, `git status` is your friend.

**Comment by hamx0r** [comment]
Thanks webron - you're so patient and helpful!  

I'm hoping pull #352 will cover the changes of both files correctly.  I was able to simply modify both files in the https://github.com/hamx0r/swagger-js fork then make a PR back to the official 2.0 branch - all using the web interface (no git CLI or windows GUI tools).  It wasn't clear when i started editing the codebase here that it made a fork of the whole codebase.   Still learning the how git works!

**Comment by dmyers** [comment]
Is there a way to add support for referenced schemas? I have title attribute on all of my schemas, but ones that are referenced are not using the title though.

ss

**Comment by dmyers** [comment]
@hamx0r Is there a way to add title support for referenced schemas? I have a title property on all of my schemas, but ones that are referenced are not using the title though.

ss

ss2

**Comment by hamx0r** [comment]
@dmeyers, good question!  The code changes i made in this PR make use of `schema.title` whenever it's present, whether from a referenced schema or not.  It appears the problem is with referenced schemas not populating the `schema` object attributes in the javascript code.  Fixing this will involve examining different code than that handled in this PR - perhaps a new change request should be created?

**Comment by venkataharishbillapati** [comment]
Is this issue fixed? I am still facing this problem.

**Comment by webron** [comment]
@venkataharishbillapati which version do you use?

**Pull request closed without merging**
