### PR TITLE
Path parameter loops would include functions in the prototype to parameters array

### PR DESCRIPTION
**Pull request by alechirsch**
Although it looks like a lot has changed, I have only added 6 lines to the code. The rest of the changes are because of indentations.

I needed to add a conditional for three of the for-in loops that tests for hasOwnProperty().
My use case for this is that I am using Swagger-UI in an Ember application, and Ember automatically converts all arrays to Ember arrays. Ember arrays have a few dozen functions attached to the prototype, which were being caught by the for-in loop.

The result of this displayed all of the Ember array function names in the parameters list for every path.

### CODE REVIEW

**Comment by fehguy** [comment]
Can you please rebase to remove the formatting changes?  It's very hard to see what has changed, and what it may affect as-is.

**Comment by alechirsch** [comment]
Sure, do you have an idea for how to do that? I am not familiar with rebasing.

I found [this](http://blog.ranjansakalley.com/2015/09/cleaning-up-whitespace-changes-in-a-pull-request.html) online, is there an easier way?

**Comment by webron** [comment]
@alechirsch simply sync swagger-js's master branch to your own branch. That would lead to conflicts which you'll need to resolve, probably manually. Once that's done, push the changes from your local branch to the remote github branch, and that will automatically update the PR which would allow us to merge it.

**Comment by alechirsch** [comment]
@webron @fehguy Is this any better? There are no conflicts when I try to merge from swagger-js master.

**Comment by alechirsch** [comment]
@fehguy @webrown Checking in on the status of this PR. Have you had a chance to look at it?

**Comment by fehguy** [comment]
@alechirsch sorry for lagging.  If you could please rebase to master I can merge this.

**Comment by alechirsch** [comment]
@fehguy It looks like this issue was resolved in #899

**Comment by fehguy** [comment]
Thank you

**Pull request closed without merging**
