### PR TITLE
Refactorings in auth.js

### PR DESCRIPTION
**Pull request by aurelian**
Small changes to make the code more understandable.

 * extract ```for``` loops to methods
 * removed extra parameter ```authorizations``` which was not used

### CODE REVIEW

**Comment by mohsen1** [comment]
Please make this pull request to `develop_2.0` branch

**Comment by aurelian** [comment]
@mohsen1 will do, but maybe is worth merging ```master``` into ```develop_2.0``` first?

**Comment by mohsen1** [comment]
We merge to master when we release. You can use `git cherry-pick` to bring your commits to develop_2.0 without worrying about master and develop_2.0 not being even.

You would need to  create another PR and close this one.

**Comment by aurelian** [comment]
@mohsen1 done in #266.

**Pull request closed without merging**
