### PR TITLE
Avoid URL encoding header values

### PR DESCRIPTION
**Pull request by duncanhall**
Fix for https://github.com/swagger-api/swagger-js/pull/226

Resubmitted after branching from the wrong place

### CODE REVIEW

**Comment by fehguy** [comment]
If you look at the src structure and gulp tasks, you'll see that swagger-client is built from files under src/js. When running gulp build, your changes will be lost. Please modify the src contents

**Comment by duncanhall** [comment]
@fehguy I'm not sure I follow? The changes were made to `src/js/swagger-a.js`. The `swagger-client` file has changes because I built and tested and then committed - and the lib folder is not `.gitignored`.

**Comment by fehguy** [comment]
My bad, scrolled past that part of the commit. Sorry!

**Comment by duncanhall** [comment]
Ha, no worries. Thanks!

**Pull request merged**
