### PR TITLE
replace isomorphic-fetch dependency by fetch-everywhere

### PR DESCRIPTION
**Pull request by jpoutrin**
I came across some nasty issue on react native.
here is a solution that was suggested in some other projects.

tests are passing fine.

### CODE REVIEW

**Comment by buunguyen** [comment]
Hi, thanks for the PR. I want to make sure I understand the motivation of the lib change. Did you mean the old lib doesn't support React Native? Or what is the issue?

**Comment by jpoutrin** [comment]
@buunguyen yes the current does not support react native 
the solution was inspired by https://github.com/agraboso/redux-api-middleware/pull/120
the current implementation does not initialize some global variables properly.

**Comment by jpoutrin** [comment]
@buunguyen please do not merge the change.
The issue  seems deeper than that.
I messes up the final react-native bundle for some reason.
it seems to be a webpack bundling issue. (one might not exclude the other).
I am no expert in webpack so this should be put on hold or discarded...

symptoms in my app when debugging:
`Failed to print error:  regeneratorRuntime.async is not a function`

symptoms without:
client.apis is empty

if someone has an idea would appreciate.

sorry for that.

**Comment by jpoutrin** [comment]
I opened an issue for this:
https://github.com/swagger-api/swagger-js/issues/1047

**Pull request closed without merging**
