### PR TITLE
Don't warn when produces is "*/*".

### PR DESCRIPTION
**Pull request by joeheyming**
Resubmit pull request to develop_2.0 branch

### CODE REVIEW

**Comment by ponelat** [comment]
@joeheyming could you also make sure you're working on develop_2.0?
So that the PR would be `develop_2.0` -> `develop_2.0`
If you're unsure, just look at the commits and make sure yours are the only ones in the PR.

.... Also (i just had a look at your commit) you've just changed the built file
Here is a quick rundown....
make sure you're on the `develop_2.0` branch
find the source file (under `lib`), that's giving you a headache, change it
build the files, like so...
```bash
npm install 

# if you have gulp installed globally...
gulp
# if you don't then ...
npm run build
```
see if it works. or add tests.
commit your change + the built files
create a PR against swagger-api/swagger-js on the `develop_2.0` branch

Thanks... seems like a lot of work, but should be under 8min :D And if you get stuck, I'll be around.

**Comment by joeheyming** [comment]
Sorry for failing using git so much

**Comment by ponelat** [comment]
Not at all! Github can be a pain sometimes... we're glad for your assistance :D

**Comment by joeheyming** [comment]
Ok, I added some tests and am working on the develop_2.0 branch, I'm gonna try again

**Comment by webron** [comment]
Shall we close this one until the new one is submitted?

**Comment by joeheyming** [comment]
@webron  in general, do I need to do a build before I push to my remote branch?  Does my commit only need the changes to operation.js?

**Comment by webron** [comment]
@ponelat?

**Comment by joeheyming** [comment]
sure, close this one.

**Comment by ponelat** [comment]
@joeheyming yes, you need build before commit, then push. This is for both swagger-ui and swagger-js in general

**Comment by joeheyming** [comment]
hmmm, when i run "npm run build", I see changes that are unrelated to mine.  I'm wondering if my branch is not correct.

**Comment by joeheyming** [comment]
git branch -vv
* develop_2.0 064a95a [origin/develop_2.0] Merge pull request #464 from ponelat/feature/default-to-application-json-if-we-can

**Comment by ponelat** [comment]
@joeheyming that's ok, it can be a 3rd party lib. I had hoped we'd solved it with the npm-shrinkwrap file, but there may still be some commits, that make things bounce around

**Pull request closed without merging**
