### PR TITLE
Add optional promise support to swagger-js

### PR DESCRIPTION
**Pull request by martinwoitzik**
Hi there,
as mentioned in #207 : 
I added 'q' to the package-dependencies to add the lightweight q-library for using promises.
With this pull-request it is now possible to use the "then/catch" notation when initializing swagger and also when executing an api-call, e.g. 
```javascript
swagger.pet.getPetbyId({petId: 3}).then(function(pet) { .... }).catch(function(error) { ... });
```

The callback-functionality is still available for backwards compatibility. If you want to enable promises, just set the "usePromise" flag to true:

```javascript
var swaggerWithPromise = new SwaggerClient({
    url: "http://petstore.swagger.io/api/api-docs",
    usePromise: true
}).then(function(swagger) { 
    ... 
}).catch(function(error) {
    ...
});
```

You can see a full example with multiple then()-chaining if you open the "index.html" from the "browser" folder.

Cheerio!
Martin

### CODE REVIEW

**Comment by martinwoitzik** [comment]
Mmmhh... don't get it - it's green when I run gulp test locally?! The travis error message doesn't make sense because the url-variable where "substring" is called should be available.

**Comment by coreylight** [comment]
Not sure if this is related, but when I try to use your branch I get:
`Cannot find module '../../node_modules/q/q' from 'myowndirectories.../node_modules/swagger-client/lib/types'`

**Comment by martinwoitzik** [comment]
Did you execute 'npm install' ?

**Comment by martinwoitzik** [comment]
Any update on this? Could you get it to work?

**Comment by coreylight** [comment]
Thanks for following up, I went a different route for now. I figured when I did a global npm install it would have "just worked". Maybe it was just my environment.

**Comment by martinwoitzik** [comment]
Alright - so, are you going to merge my request?

**Comment by coreylight** [comment]
I'm not the maintainer...just a friend.  :)

**Comment by dustinsmith1024** [comment]
:+1:  Just wondering, when does a new version get pushed to NPM?

**Comment by fehguy** [comment]
it's done manually on release, and it looks like this was pushed as 2.1.6.  We don't push when issues are closed, which may be a bit confusing.

**Comment by dustinsmith1024** [comment]
Alright, maybe I am confused. I am not getting this code when I download the latest from NPM. Your saying it should be there?

**Comment by webron** [comment]
What @fehguy is saying is that a version including this change is not pushed into NPM yet as this version hasn't been released.

**Comment by marcellodesales** [comment]
@webron @fehguy When will this be released??? Desperately need this...

**Comment by fehguy** [comment]
@marcellodesales we should have this released this Friday.  In the meantime you can pull the source and build from master to pick up support

**Comment by marcellodesales** [comment]
Thanks @fehguy... Exactly what I did!!! :) Thanks a lot!

**Comment by bkonetzny** [comment]
I have the same issue as @coreylight described earlier, I get the following:
`Cannot find module '../../node_modules/q/q' from '.../node_modules/swagger-client/lib/types'`

Why is the `q` module referenced with an relative path an not just `require('q')`? When installing with npm 3x I get this error as modules are laid out differently and thus the path doesn't match. On npm 2x I get no issue and all works as expected.

Should I open up a new issue for this?

**Comment by fehguy** [comment]
hi @bkonetzny, I'm still getting the release out.  If you watch the repo, you'll get an announcement when it is done, but for now, you'll have to build from source.

For the error you're describing, yes, you are correct, it should simply be `require('q')`.

**Comment by bkonetzny** [comment]
@fehguy See you fied it in `lib/client.js` but it's also in `lib/types/operation.js`.

**Comment by fehguy** [comment]
thanks--done.

**Pull request merged**
