### PR TITLE
New bundle option that creates an index.js file in umd. 

### PR DESCRIPTION
**Pull request by rezpe**
I have added a new task in package.json. It bundles the app in the folder umd and the filename is named index.js. This would enable to use the library from unpkg directly.
This change do not affect the tests nor the code.

Related to issue #1120

### CODE REVIEW

**Comment by rezpe** [comment]
I do not get why this merge is failing since it is not touching anything on the original codebase ...

**Comment by shockey** [comment]
@rezpe, fear not, looks like this is a problem with our CI server. Looking into it!

**Comment by rezpe** [comment]
@shockey , Could you rerun the jenkins tests ?

**Comment by shockey** [comment]
@rezpe, turns out this is being caused by a Node.js issue (https://github.com/nodejs/node/issues/22857), I'm going to have our CI switched over to v8.11.4 - stand by 😄

**Comment by shockey** [comment]
jenkins, please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
please build

**Comment by shockey** [comment]
OK - there we go 😄

**Comment by rezpe** [comment]
@shockey , Can we merge this please ?

**Comment by shockey** [comment]
Oops - made a mess of the commits here, see #1399 😓

**Pull request closed without merging**
