### PR TITLE
Fix tooltips within objects

### PR DESCRIPTION
**Pull request by joeladdison**
Fix issue with tooltips, as reported in #674. 

Also applies to swagger-api/swagger-ui#1836

### CODE REVIEW

**Comment by fehguy** [comment]
@bodnia I know you're working on moving this logic to swagger-ui--can you please confirm this is OK, and if so that it moves to the UI code?

**Comment by bodnia** [comment]
Hello Tony,

I'll check this issue and let you know when I am next to my laptop.

Thanks,
Anna

On 16 ???. 2016 ?., at 18:44, Tony Tam <notifications@github.com<mailto:notifications@github.com>> wrote:


@bodnia<https://github.com/bodnia> I know you're working on moving this logic to swagger-ui--can you please confirm this is OK, and if so that it moves to the UI code?

-

**Comment by fehguy** [comment]
No problem!

**Comment by bodnia** [comment]
@fehguy Checked, looks ok. Moved this to swagger-ui too.

**Pull request merged**
