### PR TITLE
Failing test: escaping inconsistent to requestInterceptor

### PR DESCRIPTION
**Pull request by srl295**
For: https://github.com/swagger-api/swagger-js/issues/1220

`npm t` gives:
>  Error: Expected 'percent-twentyseven' to equal 'quote'

* Request has a quote (') in it
* The interceptor sees req.url ending in quote (') which is a perfectly valid thing for a URL to end in…
* However, the xmock  shows the actual URL ends in /%27

### Description

Utterly fails. (see issue above, PR not ready to merge)

### Types of changes

- [ ] No code changes (changes to documentation, CI, metadata, etc)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shockey** [comment]
Thanks for the failing tests - I'll do my best to find some time to figure out what's going on.

**Comment by srl295** [comment]
It's Fetch that escapes

**Comment by char0n** [comment]
@srl295 would be able to rebase this PR on top of current swagger-js? Thank you!

**Comment by srl295** [comment]
@char0n I'll try!

**Comment by srl295** [comment]
@char0n done! 5e17a17

**Comment by char0n** [comment]
The moment we switch to node-fetch@3.x, these tests should pass, and I'll incorporate them into codebase.  @srl295 thanks again!

**Comment by srl295** [comment]
> The moment we switch to [node-fetch@3.x](mailto:node-fetch@3.x), these tests should pass, and I'll incorporate them into codebase. @srl295 thanks again!

Welcome, thank you for swagger!

**Comment by char0n** [comment]
@srl295 took five years, but you test have been finally integrated in  https://github.com/swagger-api/swagger-js/pull/3137/commits/f9207bd1d2663e87d10cdab7ff5b9aefe026c8fa  ;]

Thank you!

**Comment by srl295** [comment]
> @srl295 took five years, but you test have been finally integrated in  https://github.com/swagger-api/swagger-js/pull/3137/commits/f9207bd1d2663e87d10cdab7ff5b9aefe026c8fa  ;]
> 
> 
> 
> Thank you!

Welcome!

**Pull request closed without merging**
